### ISSUE TITLE
enable blockchain and binary consensus to live in same branch

### ISSUE THREAD

**Issue by djrtwo** [vladzamfir/cbc-casper#26]
# Issue
Blockchain and Binary consensus live in separate branches and are currently in conflict with each other. Goal is to make underlying components modular enough so different consensus protocols can use the same underlying structure/tools.

# Proposed Implementation

**Comment by naterush** [comment]
Merged in this PR: https://github.com/vladzamfir/cbc-casper/pull/92

Yay!
